chore: githooks config

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -2,7 +2,7 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 if ! head -1 "$1" | grep -qE "^(feat|fix|hotfix|chore|docs|test|style|refactor|perf|build|ci|revert|release)(\(.+?\))?: .{1,}$"; then
-    echo "Missing commit type: feat, fix, chore, docs, test, style, refactor, perf, build, ci, revert, release." >&2
+    echo "Missing commit type: feat, fix, chore, docs, test, style, refactor, perf, build, ci, revert." >&2
 #    exit 1
 fi
 
