chore: githooks config

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -2,15 +2,10 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 if ! head -1 "$1" | grep -qE "^(feat|fix|hotfix|chore|docs|test|style|refactor|perf|build|ci|revert|release)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
-    exit 1
-fi
-
-if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
-    echo "Aborting commit. Your commit message is too long. Message must be less than 88 characters." >&2
-    exit 1
+    echo "Missing commit type: feat, fix, chore, docs, test, style, refactor, perf, build, ci, revert, release." >&2
+#    exit 1
 fi
 
 npx commitlint --edit ${1}
-
+echo "-------------------------------------------"
 .git/hooks/commit-msg $1
